name: Rhino Linux Image Generation

on:
  workflow_dispatch

jobs:
  build_amd64:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3.5.0

    - name: Install needed packages
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/jammy/.\/devel/g' /etc/apt/sources.list
        sudo apt-get update && sudo apt-get install --reinstall debootstrap -y
        sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/lunar
        sudo dpkg -i debs/live-build_*_all.deb
        sudo mv /usr/share/debootstrap/functions functions
        sudo patch -i 0002-remove-WRONGSUITE-error.patch
        sudo mv functions /usr/share/debootstrap/functions
        sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi

    - name: Make scripts executable
      run: chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/

    - name: Build ISO
      run: |
        sudo ./build.sh etc/terraform.conf
        echo "ISOX64=$(cd builds/amd64; ls *.iso)"  >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.ISOX64 }}
        path: builds/amd64/${{ env.ISOX64 }}
        
  build_arm64:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3.5.0

    - name: Install needed packages
      run: |
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/jammy/.\/devel/g' /etc/apt/sources.list
        sudo apt-get update && sudo apt-get install --reinstall debootstrap -y
        sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/lunar
        sudo dpkg -i debs/live-build_*_all.deb
        sudo mv /usr/share/debootstrap/functions functions
        sudo patch -i 0002-remove-WRONGSUITE-error.patch
        sudo mv functions /usr/share/debootstrap/functions
        sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi
        
    - name: Make scripts executable
      run: chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/

    - name: Build ISO
      run: |
        sudo ./build.sh etc/terraform.conf
        echo "ISOA64=$(cd builds/arm64; ls *.iso)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.ISOA64 }}
        path: builds/arm64/${{ env.ISOA64 }}

  build_pine_tarball:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        ref: 'pinephone'

    - name: Install needed packages
      run: |
        sudo rm -rf /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/jammy/.\/devel/g' /etc/apt/sources.list
        sudo apt-get update && sudo apt-get install debootstrap mtools dosfstools qemu-user-static binfmt-support -y
        sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/lunar
        sudo dpkg -i debs/live-build_*_all.deb
        sudo mv /usr/share/debootstrap/functions functions
        sudo patch -i 0002-remove-WRONGSUITE-error.patch
        sudo mv functions /usr/share/debootstrap/functions
        sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi
        sudo cp binary_rootfs /usr/lib/live/build/binary_rootfs
        
    - name: Make scripts executable
      run: chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/

    - name: Build tarball
      run: |
        sudo ./build.sh etc/terraform.conf
        echo "PTAR=$(sha256sum binary/Rhino*.tar)" >> $GITHUB_ENV
      
    - uses: actions/cache@v3.3.1
      with:
        path: binary/
        key: tarball-pine-${{ env.PTAR }}

  deploy_pinephone_pro:
    needs: build_pine_tarball
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        ref: 'pinephone'
    
    - uses: actions/cache@v3.3.1
      with:
        path: binary/
        key: tarball-pine-${{ env.PTAR }}
        
    - name: Deploy to partition
      run: sudo ./debos-docker -m 10G pinephonepro.yaml
      
    - name: Place output folder
      run: sudo mkdir -p builds/pinepro
      
    - name: Move to output folder and compress
      run: |
        sudo mv Rhino*pro.img builds/pinepro/
        sudo xz -v builds/pinepro/Rhino*pro.img
        echo "IMGPPP=$(cd builds/pinepro; ls *.img.xz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.IMGPPP }}
        path: builds/pinepro/${{ env.IMGPPP }}

  deploy_pinephone:
    needs: build_pine_tarball
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        ref: 'pinephone'
    
    - uses: actions/cache@v3.3.1
      with:
        path: binary/
        key: tarball-pine-${{ env.PTAR }}
    
    - name: Deploy to partition
      run: sudo ./debos-docker -m 10G pinephone.yaml
      
    - name: Place output folder
      run: sudo mkdir -p builds/pine64
      
    - name: Move to output folder and compress
      run: |
        sudo mv Rhino*pinephone.img builds/pine64/
        sudo xz -v builds/pine64/Rhino*pinephone.img
        echo "IMGPP=$(cd builds/pine64; ls *.img.xz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.IMGPP }}
        path: builds/pine64/${{ env.IMGPP }}

  build_rpi_tarball:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        ref: 'rpi'

    - name: Install needed packages
      run: |
        sudo rm -rf /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm -rf /var/lib/apt/lists/*
        sudo sed -i 's/jammy/.\/devel/g' /etc/apt/sources.list
        sudo apt-get update && sudo apt-get install debootstrap -y
        sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/lunar
        sudo dpkg -i debs/live-build_*_all.deb
        sudo mv /usr/share/debootstrap/functions functions
        sudo patch -i 0002-remove-WRONGSUITE-error.patch
        sudo mv functions /usr/share/debootstrap/functions
        sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi
        
    - name: Make scripts executable
      run: chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/

    - name: Build tarball
      run: |
        sudo ./build.sh etc/terraform.conf
        echo "RTAR=$(sha256sum binary/Rhino*.tar)" >> $GITHUB_ENV
      
    - uses: actions/cache@v3.3.1
      with:
        path: binary/
        key: tarball-rpi-${{ env.RTAR }}

  deploy_rpi_desktop:
    needs: build_rpi_tarball
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:     
    - uses: actions/checkout@v3.5.0
      with:
        ref: 'rpi'
    
    - uses: actions/cache@v3.3.1
      with:
        path: binary/
        key: tarball-rpi-${{ env.RTAR }}
        
    - name: Deploy to partition
      run: sudo ./debos-docker -m 10G raspberrypi-desktop.yaml
      
    - name: Place output folder
      run: sudo mkdir -p builds/rpi-desktop
      
    - name: Move to output folder and compress
      run: |
        sudo mv Rhino*rpi-desktop.img builds/rpi-desktop/
        sudo xz -v builds/rpi-desktop/Rhino*rpi-desktop.img
        echo "IMGRPD=$(cd builds/rpi-desktop; ls *.img.xz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.IMGRPD }}
        path: builds/rpi-desktop/${{ env.IMGRPD }}

  deploy_rpi_server:
    needs: build_rpi_tarball
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:     
    - uses: actions/checkout@v3.5.0
      with:
        ref: 'rpi'
    
    - uses: actions/cache@v3.3.1
      with:
        path: binary/
        key: tarball-rpi-${{ env.RTAR }}
        
    - name: Deploy to partition
      run: sudo ./debos-docker -m 10G raspberrypi-server.yaml
      
    - name: Place output folder
      run: sudo mkdir -p builds/rpi-server
      
    - name: Move to output folder and compress
      run: |
        sudo mv Rhino*rpi-server.img builds/rpi-server/
        sudo xz -v builds/rpi-server/Rhino*rpi-server.img
        echo "IMGRPS=$(cd builds/rpi-server; ls *.img.xz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.IMGRPS }}
        path: builds/rpi-server/${{ env.IMGRPS }}








