name: RL PineTab Generation

on:
  workflow_dispatch

jobs:
  build_tab_tarball:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'pinetab'

    - name: Install needed packages
      run: |
        sudo rm -rf /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm -rf /var/lib/apt/lists/*
        sudo apt-get update && sudo apt-get install debootstrap mtools dosfstools qemu-user-static binfmt-support -y
        sudo ln -sfn /usr/share/debootstrap/scripts/gutsy /usr/share/debootstrap/scripts/lunar
        sudo dpkg -i debs/live-build_*_all.deb
        sudo mv /usr/share/debootstrap/functions functions
        sudo patch -i 0002-remove-WRONGSUITE-error.patch
        sudo mv functions /usr/share/debootstrap/functions
        sudo cp binary_grub-efi /usr/lib/live/build/binary_grub-efi
        sudo cp binary_rootfs /usr/lib/live/build/binary_rootfs
        
    - name: Make scripts executable
      run: chmod -R +x build.sh etc/auto/config etc/terraform.conf etc/

    - name: Build tarball
      run: sudo ./build.sh etc/terraform.conf
      
    - uses: actions/cache@v4
      with:
        path: binary/
        key: tar-tab-${{ github.run_id }}

  deploy_tab1:
    needs: build_tab_tarball
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'pinetab'
    
    - uses: actions/cache@v4
      with:
        path: binary/
        key: tar-tab-${{ github.run_id }}
        
    - name: Deploy to partition
      run: source ./etc/terraform.conf && VER="${VERSION}${SUBVER}" && sudo ./debos-docker -t image:"Rhino-Linux-${VER}-pinetab.img" -m 10G pinetab.yaml
      
    - name: Place output folder
      run: sudo mkdir -p builds/tab
      
    - name: Move to output folder and compress
      run: |
        sudo mv Rhino*tab.img builds/tab/
        sudo xz -v builds/tab/Rhino*tab.img
        echo "IMGPTA=$(cd builds/tab; ls *.img.xz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ env.IMGPTA }}
        path: builds/tab/${{ env.IMGPTA }}
        
  deploy_tab2:
    needs: build_tab_tarball
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'pinetab'
    
    - uses: actions/cache@v4
      with:
        path: binary/
        key: tar-tab-${{ github.run_id }}
        
    - name: Deploy to partition
      run: source ./etc/terraform.conf && VER="${VERSION}${SUBVER}" && sudo ./debos-docker -t image:"Rhino-Linux-${VER}-pinetab2.img" -m 10G pinetab2.yaml
      
    - name: Place output folder
      run: sudo mkdir -p builds/tab2
      
    - name: Move to output folder and compress
      run: |
        sudo mv Rhino*tab2.img builds/tab2/
        sudo xz -v builds/tab2/Rhino*tab2.img
        echo "IMGPTB=$(cd builds/tab2; ls *.img.xz)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ env.IMGPTB }}
        path: builds/tab2/${{ env.IMGPTB }}
